### ISSUE TITLE
Handle server errors

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/next-update-stats#3]
Without using nodemon

**Comment by srinivasweb4u** [comment]
where we can Set environment variables to whatever MongoDB expects

**Comment by bahmutov** [comment]
not sure I understand the question, can you clarify @srinivasweb4u ?

**Comment by srinivasweb4u** [comment]
Thanks for u reply
Set environment variables to whatever MongoDB expects

export STATS_DB_USERNAME=username
export STATS_DB_PASSWORD=password

Canu u give me clarification where i want to change. I am not much expert in mongodb .

After installation npm modules 
$ npm start

> next-update-stats@0.0.4 start D:\jade
> node ./node_modules/nodemon/nodemon.js app.js

30 Sep 17:31:01 - [nodemon] v0.7.10
30 Sep 17:31:01 - [nodemon] to restart at any time, enter `rs`
30 Sep 17:31:01 - [nodemon] watching: D:\jade
30 Sep 17:31:02 - [nodemon] starting `node app.js`
Failed to load c++ bson extension, using pure JS version
D:\jade\node_modules\check-types\src\check-types.js:417
                throw new Error(unemptyString(message) ? message : defaultMessage);
                ^

Error: missing username
    at Object.unemptyString (D:\jade\node_modules\check-types\src\check-types.js:417:23)
    at module.exports (D:\jade\db\init.js:15:10)
    at Object.<anonymous> (D:\jade\app.js:39:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
30 Sep 17:31:04 - [nodemon] app crashed - waiting for file changes before starting...

iam getting this error could u resolve

**Comment by bahmutov** [comment]
You can pass them as env variables, or see my module called "as-a"

**Comment by srinivasweb4u** [comment]
could u give me link

**Comment by bahmutov** [comment]
npm home as-a
